[package]
name = "print-organizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
env_logger = "0.10"
log = "0.4"
bytemuck = { version = "1", features = ["derive"] }
eframe = { version = "0.33.3", features = ["wgpu"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
